### ISSUE TITLE
How to get  crashlyticsApiKey without installing fabric plugin?

### ISSUE THREAD

**Issue by BoydYang** [AndroidBootstrap/android-bootstrap#139]
I cannot run because of crashlyticsApiKey.

But the fabric needs installing some plugin to my IDE, I think some people doesn't like that way. (Xcode-Ghost?)

How to disable crashlytics?

**Comment by sunyuyangg555** [comment]
hello ,this project is great, your problem is very sample,   you can do like this
manifestPlaceholders = [  
fabricCrashlyticsApiKey: "any thing"  ]
and  you also need install Fabric plugin 
http://stackoverflow.com/questions/25060008/crashlytics-developer-tools-error-when-building-android-gradle-project

**Comment by MissCoconut** [comment]
I'v already installed fabric , where can i get my fabricCrashlyticsApiKey?

**Comment by dleffler** [comment]
If you just want it to compile, just replace the (variable name) fabricCrashlyticsApiKey with  a string (in quotes) "anything".  Generally if you click on the error, it'll open up the correct file and be set to the line you need to edit.

**Comment by donnfelker** [comment]
Dan Lew has a great post on how to get it here. http://blog.danlew.net/2015/02/20/setting-up-a-new-app-in-crashlytics-without-the-plugin/
